name: Build and Push Docker Image

on:
  push: 
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Login to Docker hub
      uses: docker/setup-buildx-action@v1
      with:
      username: ${{secrets.DOCKERHUB USERNAME}}
      password: ${{secrets.DOCKERHUB PASSWORD}}
    - name: Build and Push Docker Image
      uses: docker/setup-buildx-action@v2
      name: build and push backend
      uses: docker/build-push-actions@v1
      witch: 
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{secrets.DOCKERHUB USERNAME}}/backend:lates
        
  frontend:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: login to dodcker hub
    uses: docker/login-action@v1
    witch:
      username: ${{secrets-DOCKERGUB USERNAME}}
      PASSWORD: ${{secrets-DOCKERGUB PASSWORD}}
    - name : set up docker buildx
      uses: docker/setup-buildx-action@v1
      name: build and push frontend
      uses: docker/build-push-actions@v5
      witch:
      contex: ./frontend
      file: ./frontend/Dockerfile
      push: true
      tags: ${{secrets.DOCKERHUB USERNAME}} //frontend:latest
      
