name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: https://github.com/DFAle/proyectohia.git#f26cfe34a7d5fb22859b6878af69680fd57c1fa1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        path: ./backend  # Cambiado de 'context' a 'path'
        dockerfile: ./backend/Dockerfile  # Cambiado de 'file' a 'dockerfile'
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/backend:latest

  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: set up docker buildx
      uses: docker/setup-buildx-action@v1
      with:
        context: ./frontend
    - name: build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/frontend:latest

#