name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Verificar contenido del directorio antes de construir
      run: ls -al ./backend

    - name: Resolver dependencias localmente
      run: npm install
      working-directory: ./backend

    - name: Login to Docker Hub
      uses: docker/setup-buildx-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/backend:latest



  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3
      with:
        context: ./frontend
    - name: build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/frontend:latest

##